### ISSUE TITLE
Error in ads129x.h

### ISSUE THREAD

**Issue by chessweb01** [adamfeuer/ADS129x-tools#3]
The constants for the individual channel gain settings in file ads129x.h are OK for the ADS1298 chip (see data sheet page 71, table 22) but not for the ADS1299 chip (see data sheet page 44).

**Comment by adamfeuer** [comment]
@chessweb01 Thanks- will check this out this weekend.

**Comment by adamfeuer** [comment]
@chessweb01 You are right. I will think about how to fix this and let you know - should be able to do a fix this weekend.

Thank you for finding this!

**Comment by adamfeuer** [comment]
* [ADS1298 datasheet](http://www.ti.com/lit/ds/symlink/ads1298.pdf)
* [ADS1299 datasheet](http://www.ti.com/lit/ds/symlink/ads1299.pdf)

@chessweb01

**Comment by adamfeuer** [comment]
@chessweb01 Fixed in #12

**Comment by adamfeuer** [comment]
@chessweb01 Closing
